name: space_exploration
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  provider: ^6.0.5  # Use the latest version
  intl: ^0.18.0
  http: ^1.1.0
  html: ^0.15.4
  youtube_player_iframe: ^5.2.1
  geolocator: ^11.0.0
  flutter_animate: ^4.5.2 
  permission_handler: ^11.3.0
  flutter_countdown_timer: ^4.1.0
  confetti: ^0.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#000000" # background color (black in your case)
  image: assets/photos/spacelogo.png # your custom logo
  android: true
  ios: true
  web: false


flutter_icons:
  android: true
  ios: true
  image_path: "assets/photos/spacelogo.png"



flutter:
  uses-material-design: true
  assets:
    - assets/photos/


